### ISSUE TITLE
Selfie_SHOOT

### ISSUE THREAD

**Issue by thetobyde** [BrianHepler/MMM-Selfieshot#1]
Hey dude! Very very nice! I love it so much <3 but is it possible to have a button with „take a selfie“ or something else for my touch screen MM? Maybe with an other module to send this notification to activate the countdown? I did not find anything. :/ 
In love Toby

**Comment by eouia** [comment]
This module itself has no `touchscreen button` natively. But if you have any module which can emit user-custom notification (For example; MMM-Touch, MMM-Hotword, ... ) or can emit any notification (For example; PIR or HWButton or ... their notifications could be translated through MMM-NotificationTrigger. Even `clock` module can do that. - if you want to take a photo per seconds. :D), 

Maybe @BrianHepler - new owner of this module has another idea. :) Good luck.

**Comment by BrianHepler** [comment]
It sounds like MMM-Touch is the way to implement this. I'll experiment with it and see if I can make it work easily. If so, I'll add it to the documentation. Would that be sufficient?

**Comment by thetobyde** [comment]
That would be great! Thanks a lot! I Made about 20 mirrors last weeks. For my friends... Your module is perfect for all of us. Thx.

**Comment by BrianHepler** [comment]
New code is up in the dev-button branch. Would you like to try it before I push it to the master branch?

**Comment by thetobyde** [comment]
Yes! Thx! I‘ll try it tomorrow. Thank u Brian 

Von meinem iPhone gesendet

**Comment by BrianHepler** [comment]
Merged.
