### ISSUE TITLE
How to rotate preview

### ISSUE THREAD

**Issue by gkchim** [BrianHepler/MMM-Selfieshot#13]
My preview needs to be rotated by 90 degrees because I have my monitor in portrait mode.

Is this possible?

Thanks

**Comment by hclausd** [comment]
Hello Brian,
I was wondering, if there is the possibility to add a rotation option, as asked above.
node-webcam.js has a rotation option but my programming skills are too insufficient to figure out how to implement such a rotation on the level of the preview.
It would be awesome, if you could help!
Best, Hendrik

**Comment by BrianHepler** [comment]
Okay, the rotation feature has been added. If you would please try it out on the `rotate-preview` branch, I would appreciate it. It works for me, but I would like some testing before I merge it into the main branch.

**Comment by hclausd** [comment]
Thanks for the implementation and sorry for the late reply/testing, Brian! I tested the `rotation` option from your newest version (1.0.4) and it works fine with my Raspi 3B+ and Raspi 2.1 camera. 

One thing I have been wondering: Could you implement two `rotation` options: 1) for the countdown and 2) the photo preview? In my mirrors portrait orientation the countdown orientation was good, but only the photo preview was wrong by 90°.

Best, Hendrik

**Comment by BrianHepler** [comment]
Sure, that should be relatively easy. I'll get on that.

**Comment by BrianHepler** [comment]
I separated the rotation feature into two variables: `rotateCountdown` and `rotatePreview`. You can test them out by checking out the `more-rotation` branch. Give 'em a go and let me know if they work for you.

**Comment by hclausd** [comment]
Hey Brian,
thanks for this adaptation. It tested it and it works great! :-)
Best, Hendrik
