### ISSUE TITLE
Pi Cam

### ISSUE THREAD

**Issue by thetobyde** [BrianHepler/MMM-Selfieshot#2]
Hey Brian again,

We would really like to have the PiCam support. You said u can not implement this right now, cause you dont have a Pi Cam. 
Would it help to ship mine to you? 
Greetings, Toby

**Comment by BrianHepler** [comment]
I just got one in the mail, thank you. I'll get to work on this presently.

**Comment by thetobyde** [comment]
Nice Brian! You are the Best! Looking forward to use it. Will you let me now, if it works? 

Von meinem iPhone gesendet

**Comment by BrianHepler** [comment]
Okay, the touch button has been implemented. I'll see about testing this under a Pi cam now. It's coming.

**Comment by BrianHepler** [comment]
@thetobyde - Sir, I just tested this with my PiCam and it works just fine. You have to enable the camera interface via the `raspi-config` tool, but it appears to be working without any additional code from me.

**Comment by thetobyde** [comment]
Nice! So do I have to „update“ the module and it will work? Or just put the „useCam“ thing in my config? 

Von meinem iPhone gesendet

**Comment by BrianHepler** [comment]
You should be able to enter `sudo raspi-config` to bring up the configuration menu. Go to Interfacing Options and then highlight "Camera" (it should be the first entry). Enable the camera interface and then Finish. You will be asked to reboot, which you should do.

If you have a USB camera, unplug it from the Pi. Once you have a connection back to the pi, test the camera with the following command: `raspistill -o image.jpg`. When it gives you the command line back, do a `ls` to see if the file `image.jpg` is present. If it is, then your camera works.

At that point, use the MMM-Selfieshot as usual. No need to update the module. I don't know what "useCam" is. Where are you seeing this?

**Comment by mirrormonark** [comment]
hi... when use "raspistill -o image.jpg" i see this "the system should be configured for the legacy camera stack"
but when i try .. "libcamera-still -o image.jpg " my picamera Noir take me a photo. 
in 2023 I had to download the "libcamera-apps" to have the function of cameras.

I tried the normal configuration -- but nothing happens.
I also tried the configuration where it says to mash but nothing happens (I was not mashing the button as touchscreen but via mouse)

**Comment by BrianHepler** [comment]
The latest version of Raspian uses a new camera stack. You can enable the legacy camera stack by following the instructions I listed above to enable the Pi camera. It's just labeled as "legacy camera support" rather than enabling the camera entirely.
In short, use `sudo raspi-config` to get into the RPi configuration, then turn on everything camera related that you find in that interface.
