### ISSUE TITLE
Toast make image

### ISSUE THREAD

**Issue by thetobyde** [BrianHepler/MMM-Selfieshot#6]
Hey Brian! :) everything worked fine with my Pi Cam.. but suddenly it doesn't make a image now. The Countdown works, the image preview starts but there is no photo taken. raspistill -o test.jpg works.

The debug says:
<img width="534" alt="Bildschirmfoto 2020-09-06 um 02 17 38" src="https://user-images.githubusercontent.com/53558782/92315556-8bca5b80-efe7-11ea-9656-90f21d257dc0.png">

I get an Mail with the taken photo, but its not a jpg or png its just an file I can't open.

Thx for help! I need the module, its the best module for the MM! *_*

**Comment by BrianHepler** [comment]
Interesting. Can you post the relevant portion of the `config.js` please? I want to try and duplicate your problem. If I understand properly, you receive an email and there's an attachment, but you can't open the attachment. What's the name of the attachment? Does the name change from email to email or do they all have the same name? And does the attachment have any data in it, or is it zero length?

And did you make any other changes to your config in the meantime? Specifically, is there any other module that uses the camera, such as the motion detection?

**Comment by thetobyde** [comment]
Hey Brian. Thx for your time. 

This is my code in the config.js:
```
`{
			disabled: false,
			module: "MMM-Selfieshot",
			config: {
					width:1920,
					height:1080,
					device: null,
					debug:true,
					shootMessage: "Smile!",
					sendMail: {
  						transport: {
    						host: 'mail.gmx.net', // If required.
    						port: 465, // If required.
    						secure: true, // If required.
    						auth: {
      							user: "thetoby@gmx.net",
      							pass: "***********"
    							}
  						},
  						message: {
    						from: "thetoby@gmx.net",
   						to: "thetoby@icloud.com",
    						subject: "Spiegel Selfie",
    						text: "Neues Selfie.",
  							}
						}
				}
		},`
```

This is what I'll get in my Mails:
<img width="225" alt="Bildschirmfoto 2020-09-09 um 18 34 56" src="https://user-images.githubusercontent.com/53558782/92627617-ea375880-f2cb-11ea-95d4-f8f1ba42fe6e.png">


Everything worked fine, until few weeks.

**Comment by thetobyde** [comment]
I reinstalled the module and it works! Thx.

**"Have you tried to put it off and on again?"** 😂😂

**Comment by BrianHepler** [comment]
Great! I'm sorry that I wasn't more help. Let me know if it happens again.
