### ISSUE TITLE
Show webcam feed

### ISSUE THREAD

**Issue by ShadowofArya** [BrianHepler/MMM-Selfieshot#7]
Hi,
Is it possible to show the webcam feed while the countdown is running so that you can see what's in frame when taking a photo?

**Comment by BrianHepler** [comment]
It should be possible. I'll look into adding that as a feature. Good idea!On Oct 21, 2020 18:23, ShadowofArya <notifications@github.com> wrote:
Hi,
Is it possible to show the webcam feed while the countdown is running so that you can see what's in frame when taking a photo?

**Comment by ShadowofArya** [comment]
Thank you!

**Comment by BrianHepler** [comment]
I looked into this a bit and I don't think I can do it. The current module works by setting the background of the module window to the location of the stored image on disk. I don't think I can open up a live stream without getting a video player involved and judging by the RTSP module, that's a non-trivial task.

Sorry to disappoint, but I don't have the chops for this.
