### ISSUE TITLE
DSLR integration with gPhoto2 

### ISSUE THREAD

**Issue by JimmyKnopf** [BrianHepler/MMM-Selfieshot#9]
Is there a possibility to add DSLR integration by using gPhoto2?
Would it be possible to run a costum command at the end of the count down to take a picture e.g. 'gphoto2 --capture-image-and-download'? So instead of directly taking a selfie the programm would run a command to take a picture.

**Comment by BrianHepler** [comment]
Anything is possible. Do I understand you in that you would like to use a DSLR instead of the Pi webcam or other USB camera to take the photo and have it transfer the image to the Pi for display on the screen?

**Comment by JimmyKnopf** [comment]
Great to hear :)
Yes that would be perfect. Altough if it would just run the gphoto2 command, it would already fit my needs. Everything else I could do with gphoto2.
